name: Build release archive

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create release archive
        run: zip -r vpd_air_auto_release.zip custom_components README.md CHANGELOG.md LICENSE hacs.json
      - uses: actions/upload-artifact@v4
        with:
          name: vpd_air_auto_release
          path: vpd_air_auto_release.zip
